Validation
nevisende/my-portfolio pull request #6
Opened 2021-11-10 15:24 UTC by nevisende

We created a tag to show the error message and We write functions in JS to check email validation.

2021-11-10 15:30 UTC, D4nielJ commented
Hi @nevisende, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't check for all of the linter requirements. Please update the linters of your project so they checked for JavaScript code as well. To do this remove the old ones and follow the instructions to [install HTML/CSS/JavaScript Linters.](https://github.com/microverseinc/linters-config/tree/master/html-css-js)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-11-10 21:02 UTC, taiwo2 requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-10 21:02 UTC, taiwo2 commented on index.html
>                   <button type="submit"> Start collaboration</button>
The error message should fit the design from the chosen template in Figma (colors). the color chosen should fit the design template. kindly fix it

2021-11-10 21:14 UTC, taiwo2 requested changes

2021-11-10 21:14 UTC, taiwo2 commented on index.html
>                             <input type="email" name="emial" id="email" required>
KIndly correct the spelling of your name attribute

2021-11-10 21:14 UTC, taiwo2 commented on index.html
>                             <input type="email" name="emial" id="email" required>
KIndly correct the spelling of your name attribute

2021-11-11 09:03 UTC, ignatius22 approved these changes
## Hi @nevisende, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-11 12:48 UTC, merged